### ISSUE TITLE
icecream cannot find line number when used in docker

### ISSUE THREAD

**Issue by Noskario** [lewinfox/icecream#21]
I have a shiny app where I use icecream to log what is happening. Normally it works great and even gives the filename, line and position where the `ic()` was located:
```ℹ ic| `observe()` in view0_app6.R:462:4```

However, if I open up the app in docker then the output looks like this:
```ℹ ic| `observe()` in <env: 0x55827f1fbc00>```

Is there anything I can do about it?

**Comment by lewinfox** [comment]
Hi @Noskario, thanks for this. This is a new one on me, I've never tried it in Docker.

That `<env: (something)>` output shows the function environment, and it's what `ic()` displays if it can't find a `srcref` for the function. You'd expect to see that if the function calling `ic()` wasn't sourced from a file or loaded as part of a package, for example:

``` r
# Run this in the R terminal
one <- function() { ic(); 1 }
one()
#> ℹ ic| `one()` in <env: global>
```

Or if your function is in a different environment:

``` r
new_env <- new.env()
environment(one) <- new_env
one()
#> ℹ ic| `one()` in <env: 0x55a2f6dd48d0> # The hex string will be different for you
```

There's an [example of this in the README](https://github.com/lewinfox/icecream#inspect-execution). Without seeing how your Docker container is working I'm afraid I can't offer much more, but if you can provide a reprex I'd be happy to take a look. It would be interesting if this was a Docker thing.

**Comment by lewinfox** [comment]
Hi @Noskario, if this is still a problem for you please send some kind of runnable example and I'll take a look. Otherwise I'm going to close the issue. Thanks!

**Comment by Noskario** [comment]
Sorry for having forgotten about this issue, at the time of writing this I was too overwhelmed by all those concepts. As you already told me, docker is not the root cause why there are no line numbers. Instead it seems that the setup itself is the problem:

```Rscript startapp.R```
Here we do the preparation like defining some environment variables and files and so on. `ic()` prints `ℹ ic| <env: global>'`
Within the startapp.R we also source some other files like e.g. app.R where a shiny-App is located with some ic() in the server. They now read `ℹ ic| observe() in <env: 0x000001eefe6090b8>`

I would be happy to know if this is expected and whether there is might be some easy fix.

Thanks a lot for your help from June!!!

**Comment by lewinfox** [comment]
I believe Shiny also does some fancy stuff with environments, so I'm not surprised to see that functions are showing up in environments other than `global`. I'm afraid this isn't something I can fix - it's a consequence of the way Shiny works. Sorry!
