### ISSUE TITLE
Implement `with_ic_disable()`

### ISSUE THREAD

**Issue by ErdaradunGaztea** [lewinfox/icecream#6]
It's easy to call `ic_disable()` and then forget to turn it on again. `with_ic_disable()` would run the code given as a parameter with icecream disabled and then reset icecream state back to enabled. Y'know, just what `withr` does. And -- if so, it would only make sense to include `local_ic_disable()` as well.

There are already `withr::with_()` and `withr::local_()` functions that would take care of most work needed (probably?).

Also, should it be called `with_ic_disabled()` instead?

**Comment by lewinfox** [comment]
I like this idea! I agree that `withr` is the way to go, it looks like 

``` r
with_ic_disable <- function(expr) {
  withr::with_options(list(icecream.enabled = FALSE, expr))
}
```

does basically what you're describing?

Name-wise I like `with_ic_disable()` - not usual English but I think it's best to align with the name of the `ic_disable()`  function. Would we want or need a matching `with_ic_enable()`? 

@DominikRafacz what do you think?

**Comment by DominikRafacz** [comment]
Good idea, I think one would benefit from such a function.  You've misplaced the parenthesis in your code

```r
with_ic_disable <- function(expr) {
  withr::with_options(list(icecream.enabled = FALSE), expr)
}
```

but it generaly should be sufficient :)

`with_ic_enable()` would also be reasonable in such case. I only hope that `withr` can manage to write out the context correctly, because if not, it will have to be rewritten by hand.

**Comment by lewinfox** [comment]
@ErdaradunGaztea is this something you'd like to pick up? I'm happy to do it if not :+1:  If so let me know and I'll assign it to you.

**Comment by lewinfox** [comment]
New branch [release/v0.2.0](https://github.com/lewinfox/icecream/tree/release/v0.2.0) created to hold all the new changes.
